[package]
name = "to_do"
authors = ["twertybog"]
version = "0.2.1"
edition = "2021"

[dependencies]
serde_json = "1.0.85"
fltk = "1.3.15"

[profile.dev]
lto = false
opt-level = 0


[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1


